# version: '3'

# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     healthcheck:
#       test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#       timeout: 5s
#       retries: 5
#       start_period: 60s
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###

services:
  web:
    build: './docker-build/php/'
    ports: 
      - '8006:443'
    volumes: 
      - .:/var/www/Places
    links:
      - db:db
    
  db:
    build: './docker-build/mysql/'
    volumes:
      - ~/.docker/mysql:/var/lib/mysql
    ports:
      - '3026:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=iamfree
    
  adminpaneldb:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8076:80'
    links:
      - db:db
  
  